require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/MethodCallWithArgsParentheses:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 10

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/Date:
  Enabled: false
